In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [3]:
m_train = pd.read_csv('/Users/tuhenasen/Downloads/MNIST-data 2/mnist_train.csv',header = None)
m_test = pd.read_csv('/Users/tuhenasen/Downloads/MNIST-data 2/mnist_test.csv',header = None)


In [11]:
#adding new column to check if it is odd or even
m_train['odd/even'] = m_train[0].apply(lambda x: 1 if x%2 == 0 else 0)
m_train.head()

0  1  2  3  4  5  6  7  8  9  ...  776  777  778  779  780  781  782  783  \
0  5  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  4  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  1  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  9  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   784  odd/even  
0    0         0  
1    0         1  
2    0         1  
3    0         0  
4    0         0  

[5 rows x 786 columns]

In [12]:
# select odd/even
m_train_set= m_train.iloc[:, -1].values
m_train_set

array([0, 1, 1, ..., 0, 1, 1])

In [8]:
# select feature
m_train_table = m_train.iloc[:,1:785]
m_train_feature = m_train_table.values
m_train_feature

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [9]:
m_train_set.shape

(60000,)

In [10]:
m_train_feature.shape

(60000, 784)

In [13]:
# test dataset: use if loop to identify odd and even, add a new col 
m_test['odd/even'] = m_test[0].apply(lambda x: 1 if x%2 == 0 else 0)
m_test_set = m_test.iloc[:, -1].values
m_test_set

array([0, 1, 0, ..., 1, 0, 1])

In [14]:
m_test_feature_table = m_test.iloc[:,1:785]
m_test_feature = m_test_feature_table.values
m_test_feature

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
m_test_set.shape

(10000,)

In [17]:
m_test_feature.shape

(10000, 784)

In [42]:
# FUNCTION TO GENERATE EVEN DIGIT SET

def oddevendataset (set_number, even_number):
    train = m_train.loc[m_train['odd/even'] == 0].sample(n=even_number,replace=True)
    train = train.append(m_train.loc[m_train['odd/even'] == 1].sample(n=(30000-even_number),replace=True))
    print('training dataset ',set_number,
          '\nnumber of even digits:',train[train['odd/even'] == 0].shape[0],
          '\nnumber of rows:',train.shape[0])
    return train

In [58]:
# NAIVE BAYES 

def NaiveBayes(data, X_test): 

# data split    
    y_train = data.iloc[:, -1].values
    feature_table = data.iloc[:,1:785]
    X_train = feature_table.values
    
# build model   
    #model = GaussianNB()
    model = MultinomialNB()

# Train the model using the training sets
    model.fit(X_train,y_train)

# Predict Output
    predicted= model.predict(X_test)
    
    
# Print accuracy
    Accuracy = accuracy_score(m_test_set, predicted)
    print({ 'accuracy' : Accuracy})
 

30000 images of which 300 correspond to even digits

In [59]:
training1 = oddevendataset(1,300)
model1 = NaiveBayes(training1, m_test_feature)

training dataset  1 
number of even digits: 300 
number of rows: 30000
{'accuracy': 0.7958}


In [60]:
# 30000 images of which 3000 correspond to even digits
training2 = oddevendataset(2,3000)
model2 = NaiveBayes(training2, m_test_feature)

training dataset  2 
number of even digits: 3000 
number of rows: 30000
{'accuracy': 0.8058}


In [61]:
# 30000 images of which 6000 correspond to even digits
training3 = oddevendataset(3,6000)
model3 = NaiveBayes(training3, m_test_feature)

training dataset  3 
number of even digits: 6000 
number of rows: 30000
{'accuracy': 0.8053}


In [62]:
# 30000 images of which 12000 correspond to even digits
training4 = oddevendataset(4,12000)
model4 = NaiveBayes(training4, m_test_feature)

training dataset  4 
number of even digits: 12000 
number of rows: 30000
{'accuracy': 0.8061}


In [63]:
# 30000 images of which 15000 correspond to even digits
training5 = oddevendataset(5,15000)
model5 = NaiveBayes(training5, m_test_feature)

training dataset  5 
number of even digits: 15000 
number of rows: 30000
{'accuracy': 0.8068}
